import React, { useState } from "react";
import { MainLayout } from "@/components/layout/main-layout";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { BookOpen } from "lucide-react";
import { showSuccess, showError, showLoading, dismissToast } from "@/utils/toast";
import { supabase } from "@/integrations/supabase/client";

const Summarize = () => {
  const [inputText, setInputText] = useState("");
  const [summary, setSummary] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  const handleSummarize = async () => {
    if (inputText.trim() === "") {
      showError("Please enter text to summarize.");
      return;
    }

    setIsLoading(true);
    const loadingToastId = showLoading("Generating summary...");

    try {
      // Call the Supabase Edge Function for summarization
      const { data, error } = await supabase.functions.invoke('summarize', {
        body: { text: inputText },
      });

      if (error) {
        throw error;
      }

      setSummary(data.summary);
      showSuccess("Summary generated successfully!");
    } catch (error) {
      console.error("Error summarizing text:", error);
      showError("Failed to generate summary. Please try again.");
    } finally {
      setIsLoading(false);
      dismissToast(loadingToastId);
    }
  };

  return (
    <MainLayout>
      <div className="container mx-auto py-8">
        <h1 className="text-4xl font-bold mb-4 text-primary">Summarize Your Content</h1>
        <p className="text-lg text-muted-foreground mb-8">
          Paste text below to get a concise summary generated by AI.
        </p>

        <Card className="mb-8">
          <CardHeader>
            <BookOpen className="h-8 w-8 text-blue-500 mb-2" />
            <CardTitle>Input Text for Summarization</CardTitle>
            <CardDescription>Enter the content you want to summarize.</CardDescription>
          </CardHeader>
          <CardContent>
            <Textarea
              placeholder="Paste your article, notes, or document content here..."
              value={inputText}
              onChange={(e) => setInputText(e.target.value)}
              rows={15}
              className="w-full mb-4"
              disabled={isLoading}
            />
            <Button onClick={handleSummarize} disabled={isLoading}>
              {isLoading ? "Summarizing..." : "Generate Summary"}
            </Button>
          </CardContent>
        </Card>

        {summary && (
          <Card>
            <CardHeader>
              <CardTitle>Generated Summary</CardTitle>
              <CardDescription>Here's the concise summary of your content.</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="bg-muted p-4 rounded-md text-muted-foreground whitespace-pre-wrap">
                {summary}
              </div>
            </CardContent>
          </Card>
        )}
      </div>
    </MainLayout>
  );
};

export default Summarize;